# Generated by Django 3.1.7 on 2021-02-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='todo',
            new_name='todo_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='todo_id',
            field=models.ForeignKey(blank=True, db_column='todo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.todo'),
        ),
    ]
